### ISSUE TITLE
Alfabetyczna lista osób

### ISSUE THREAD

**Issue by yetem** [Drizii/DayChallange#1]
Podczas dodawania osób do dnia fajnie by było, żęby na liście osoby były ułożone alfabetycznie.

Powinno Ci wystarczyć doadnie Meta ordering do modelu Person

https://docs.djangoproject.com/en/3.0/ref/models/options/#ordering
![Zrzut ekranu z 2020-08-04 14-55-46](https://user-images.githubusercontent.com/12342128/89296858-44a51f80-d663-11ea-9975-9821cea8e5d7.png)

**Comment by Drizii** [comment]
dodałem

> class Meta:
> ordering = ['name']

w przypadku liter różniej wielkości 
np:
"a" i "Z" w pierwszej kolejności są brane pod uwagę litery duże a dopiero później małe, czyli
litera "Z" będzie wyżej w liście niż litera "a"
z tego co widzę, wszystkie osoby są pisane z dużej litery, więc nie dodaję funkcjonalności obsługującej duże litery

**Comment by yetem** [comment]
Potwierdzam.
