### ISSUE TITLE
Ostylowanie paginacji

### ISSUE THREAD

**Issue by yetem** [Drizii/DayChallange#2]
Dobrze by było, żeby paginacja jakoś tam wyglądała.
W bootstrapie możęsz użyć:
https://getbootstrap.com/docs/4.0/components/pagination/

Ale jeżeli przejdziemy na mdbootstrap (polecam, jest ładniejszy imo) to wtedy:
https://mdbootstrap.com/docs/jquery/components/pagination/

![image](https://user-images.githubusercontent.com/12342128/89297091-a1a0d580-d663-11ea-8e21-8ee296dfd767.png)

**Comment by Drizii** [comment]
Paginacja została wykonana B)
jestem z niej dumny

tu jest filmik jak działa B)
https://www.loom.com/share/9a1e05a177ca4427ab8ebbe948defe9e

**Comment by yetem** [comment]
Potwierdzam, wygląda i działa ślicznie :D
