### ISSUE TITLE
Wyświetlanie dat /days/

### ISSUE THREAD

**Issue by Drizii** [Drizii/DayChallange#8]
aktualnie daty wyświetlają się w formacie
`AUG. 2, 2020 `

bardziej chciałbym, aby daty wyświetlały się w sposób:
dzień - miesiąc - rok
lub
(nazwa dnia tygodnia) dzień - miesiąc - rok

**Comment by Drizii** [comment]
Poprawiono daty, teraz wyświetlają się w czytelniejszy sposób

**Comment by yetem** [comment]
Potwierdzam :)
